.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TIMETIP" "1" "September 2013" "" ""
.
.SH "NAME"
\fBtimetip\fR \- time manager
.
.SH "SYNOPSIS"
\fBtimetip\fR [\fIcommand\fR] [<args\.\.\.>]
.
.SH "DESCRIPTION"
Deliciously\-minimal time tracker for the command\-line, with a very simple command\-line interface\. Timetip is able to log your tasks, as well as query them and display it nicely\.
.
.SH "SHORTHANDS"
Here are all the commands you need to get started\. These are shortened form of the \fICOMMANDS\fR below to help you do the most common tasks\.
.
.TP
\fBtimetip\fR \fInew\-task\-name\fR
Starts working on the \fItask\fR you\'re doing\. (Alias: \fBstart\fR)
.
.TP
\fBtimetip\fR \fIdate\fR|\fIrange\fR
Shows entries for the given \fIdate\fR\. (Alias: \fBshow\fR)
.
.TP
\fBtimetip\fR
Shows entries for today\. (Alias: \fBshow today\fR)
.
.TP
\fBtimetip \-\fR [\fIreason\fR]
Stops working, and logs your \fIreason\fR for the break\. (Alias: \fBstop\fR)
.
.SH "COMMANDS"
Below is a full list of commands you can use in their proper form\.
.
.TP
\fBtimetip start\fR \fInew\-task\-name\fR
Start working on \fItask\fR\. See \fITASKS\fR\.
.
.TP
\fBtimetip stop\fR [\fIreason\fR]
Stops working\. Optionally, you may give a \fIreason\fR\.
.
.TP
\fBtimetip show\fR [\fIdate\fR|\fIrange\fR|all]
Show entries for the given \fIdate\fR or \fIrange\fR, or show \fBall\fR entries\. When no arguments are given, \fBtoday\fR is assumed\. See \fIDATES AND RANGES\fR for details on the possible formats\.
.
.TP
\fBtimetip edit\fR
Opens the time log in your default text editor\.
.
.TP
\fBtimetip summary\fR [\fIdate\fR|\fIrange\fR|all]
Shows the summary for a given \fIdate\fR or \fIrange\fR\. When no arguments are given, shows the summary for all entries in the time sheet\.
.
.SH "OPTIONS"
These are general options that work with almost all of the commands\.
.
.TP
\fB\-R\fR, \fB\-\-reporter\fR \fIname\fR
Use the reporter \fIname\fR\. See \fIREPORTERS\fR for more info\.
.
.TP
\fB\-u\fR, \fB\-\-use\fR \fIpath\fR
Load the JavaScript file in \fIpath\fR as a plugin\. This is useful for making your own custom reporters or commands\.
.
.TP
\fB\-f\fR, \fB\-\-file\fR \fIpath\fR
Use the file in \fIpath\fR as the time sheet file\. See \fIFILE FORMAT\fR\.
.
.TP
\fB\-\-no\-color\fR
Disables the use of color in outputs\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Displays a help screen\.
.
.TP
\fB\-V\fR, \fB\-\-version\fR
Displays version information and exits\.
.
.SH "TASKS"
Tasks are started with the \fBtimetip start\fR command\. The convention is that the first word is always the project name \-\- this is simply for the convenience of having summaries\.
.
.IP "" 4
.
.nf

$ timetip start Meeting with Dan
.
.fi
.
.IP "" 0
.
.P
You may specify a time as well\. This is useful for when you started working without logging it first\.
.
.IP "" 4
.
.nf

$ timetip start Meeting 11:53am
.
.fi
.
.IP "" 0
.
.P
You can also specify the time as an offset in the form of \fB<duration> ago\fR, such as:
.
.IP "" 4
.
.nf

$ timetip start Meeting 15m ago
$ timetip start Meeting 3 minutes ago
.
.fi
.
.IP "" 0
.
.P
And of course, these conventions work with the \fISHORTHANDS\fR too:
.
.IP "" 4
.
.nf

$ timetip Meeting 3m ago
.
.fi
.
.IP "" 0
.
.P
Also, it works for breaks (via \fBstop\fR or \fB\-\fR):
.
.IP "" 4
.
.nf

$ timetip stop 3m ago
.
.fi
.
.IP "" 0
.
.SH "DATES AND RANGES"
The \fIdate\fR strings are parsed as natural language dates\. They can be simple dates (eg: \fBMarch 5\fR), or any reasonable format that can be figured out unambiguously (eg: \fBlast thursday\fR)\. Some examples:
.
.IP "" 4
.
.nf

$ timetip today
$ timetip september 2
$ timetip jan 20
$ timetip yesterday
$ timetip 1 month ago
$ timetip 23 days ago
.
.fi
.
.IP "" 0
.
.P
Ranges, often used for \fBshow\fR, and can be in the following formats:
.
.IP "\(bu" 4
\fIdate\fR \- \fIdate\fR
.
.IP "\(bu" 4
since \fIdate\fR
.
.IP "" 0
.
.P
Examples:
.
.IP "" 4
.
.nf

$ timetip mar 2 \- mar 5
$ timetip since last week
$ timetip last mon \- last thu
.
.fi
.
.IP "" 0
.
.SH "FILE FORMAT"
It\'s an ini file\. It is designed to be human\-editable and human\-readable, and you are encouraged to edit your time sheets outside of \fBtimetip\fR\. Files are saved to \fB~/\.timelogs\fR by default, and looks like this:
.
.IP "" 4
.
.nf

[2013\-09\-16 mon]
1:14pm = Misc write emails
2:42pm = Misc balance checkbook
3:00pm =

[2013\-09\-18 wed]
3:14pm = Jsconf email speakers
3:59pm = \-\- coffee break
4:09pm = Jsconf check ticket sales
4:25pm = Errands grocery
.
.fi
.
.IP "" 0
.
.P
The format boils down to these:
.
.IP "\(bu" 4
Dates are headings in the format of \fB[yyyy\-mm\-dd dom]\fR
.
.IP "\(bu" 4
Tasks are in the format \fB<time> = <project>\fR
.
.IP "\(bu" 4
Breaks are in the format of \fB<time> =\fR
.
.IP "\(bu" 4
Breaks with reasons are in the format of \fB<time> = \-\- <reason>\fR
.
.IP "" 0
.
.P
Note that comments (beginning in \fB;\fR) are going to be stripped\.
.
.SH "REPORTERS"
You can use custom reporters to change the display format\. By default, it comes with the following reporters:
.
.IP "\(bu" 4
\fBdefault\fR \- Default reporter for terminal viewing\.
.
.IP "\(bu" 4
\fBjson\fR \- Exports your data to JSON\.
.
.IP "\(bu" 4
\fBtmux\fR \- Displays a tmux status\.
.
.IP "" 0
.
.P
You can export your data using the \fBjson\fR reporter:
.
.IP "" 4
.
.nf

$ timetip \-\-reporter json
  {
    "date": "2013\-09\-26",
    "entries": [
      { "type": "task",
        "project": "Meeting",
        "task": "skype with Dan",
        "duration": 30000000,
        "date": "2013\-09\-26T02:40:00\.000Z",
        "endDate": "2013\-09\-26T02:40:00\.000Z" }, \.\.\.
    ]
  }
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
Here are some ways to start or stop a task:
.
.TP
$ \fBtimetip\fR Meeting with John
Starts working on "Meeting with John"\.
.
.TP
$ \fBtimetip\fR Meeting 3m ago
Starts working on "Meeting" and gives it a timestamp that\'s 3 minutes ago from now\.
.
.TP
$ \fBtimetip stop\fR
Stops the current task\.
.
.TP
$ \fBtimetip stop\fR lunch break
Stops the current task, and logs the reason for your break\.
.
.TP
$ \fBtimetip summary\fR
Shows a summary of project hours\.
.
.TP
$ \fBtimetip summary\fR since last month
Summarizes the last month\'s hours\.
.
.SH "SEE ALSO"
timetip\-extras(1)
